//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleExcelUploadExport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.LabourCategories = new HashSet<LabourCategory>();
        }
    
        public int ID { get; set; }
        public string Client { get; set; }
        public string Single_Master { get; set; }
        public string Joint_Venture { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ContractManager { get; set; }
        public string TimesheetVeriosnType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabourCategory> LabourCategories { get; set; }
    }
}
