//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleExcelUploadExport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabourCategory
    {
        public int ID { get; set; }
        public Nullable<int> Contract_ID { get; set; }
        public string ContractName { get; set; }
        public string CommonLabourCategory { get; set; }
        public string DisplayName { get; set; }
        public string ShortName { get; set; }
        public string EEO { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
